🐛 fix: 파일 확장자명 변경

diff --git a/.github/workflows/lighthouse.yml b/.github/workflows/lighthouse.yml
--- a/.github/workflows/lighthouse.yml
+++ b/.github/workflows/lighthouse.yml
@@ -47,15 +47,15 @@ jobs:
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
         run: |
           npm install -g @lhci/cli
-          lhci collect --config=.lighthouserc-desktop.js || echo 'Fail to Run Lighthouse CI 💦'
-          lhci upload --config=.lighthouserc-desktop.js || echo 'Fail to Run Lighthouse CI 💦'
+          lhci collect --config=.lighthouserc-desktop.cjs || echo 'Fail to Run Lighthouse CI 💦'
+          lhci upload --config=.lighthouserc-desktop.cjs || echo 'Fail to Run Lighthouse CI 💦'
 
       - name: Run Lighthouse CI for Mobile
         env:
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
         run: |
-          lhci collect --config=.lighthouserc-mobile.js || echo 'Fail to Run Lighthouse CI 💦'
-          lhci upload --config=.lighthouserc-mobile.js || echo 'Fail to Run Lighthouse CI 💦'
+          lhci collect --config=.lighthouserc-mobile.cjs || echo 'Fail to Run Lighthouse CI 💦'
+          lhci upload --config=.lighthouserc-mobile.cjs || echo 'Fail to Run Lighthouse CI 💦'
 
       - name: Format lighthouse score
         id: format_lighthouse_score
